language: ruby
rvm:
  - 2.4.x
  - 2.3.x
  - 2.2.x
  - 2.1.x
  - 1.9.3
  - 1.9.2
branches:
  only:
    - master
notifications:
  irc:
    channels:
      - "chat.freenode.net#cloudi"
    on_success: change
    on_failure: always
